version: 0.2

phases:
  pre_build:
    commands:
      - aws --version
      - pip3 uninstall awscli -y
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
      - yum install iputils which -y
      - which ping 
      - ping -c 10 172.31.2.156
  build:
    commands:
     # - ping -c 172.31.2.156
      - yum install samba -y
      - chmod +x passwordchanger.sh
      - ./passwordchanger.sh
  post_build:
    commands:
      - echo Build completed on `date`
#artifacts:
#  files:
#    - target/messageUtil-1.0.jar
