version: 0.1

phases:
  pre_build:
    commands:
      - aws --version
      - pip3 uninstall awscli -y
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
      - aws --version
  build:
    commands:
      - smbpasswd -U test2 -r 172.31.11.167
  post_build:
    commands:
      - echo Build completed on `date`
#artifacts:
#  files:
#    - target/messageUtil-1.0.jar
